# NumPy

- NumPy stands for 'Numerical Python'. 
- It is a Python library which consist multidimensional array objects and collection of routines for processing of array.

## NumPy is fast
- Numpy is also incredibly fast, as it has bindings to C libraries
- NumPy Arrays are faster than Python Lists because of the following reasons: An array is a collection of homogeneous data-types that are stored in contiguous memory locations

## Numpy Arrays
- NumPy arrays are of two types: 
    - vectors: Vectors are strictly 1-d arrays
    - matrices: matrices are 2-d (but you should note a matrix can still have only one row or one column).

## List vs NumPy Arrays

- In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy provide array object that is up to 50x faster than Python lists.

- The array object in NumPy is called ndarray.


# Installation

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## How to Use

In [2]:
import numpy

import numpy as np

## Creating NumPy Arrays

In [3]:
# from Pyhton List
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
x=np.array(my_list)
print(x)
type(x)

[1 2 3 4 5]


numpy.ndarray

In [5]:
a=np.array([[1,2,4,56,65,6778],[1,2,40,156,615,6778]])
print(a)

[[   1    2    4   56   65 6778]
 [   1    2   40  156  615 6778]]


## NumPy array using nested list/matrix

In [6]:
my_matrix = [[5,55,555],[6,66,666],[7,77,777],[8,88,888]]
my_matrix

[[5, 55, 555], [6, 66, 666], [7, 77, 777], [8, 88, 888]]

In [7]:
a=np.array(my_matrix)
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(a)
print(a.dtype)

[[  5  55 555]
 [  6  66 666]
 [  7  77 777]
 [  8  88 888]]
int32


##  Printing which type of data present inside numpy 
### dtype
- You can also grab the data type of the object in the array
- .dtype only works with numpy/array objects.array

In [9]:
r=np.array(["Hi","Hello","Good"])
print(r.dtype)

<U5


## Built-in Methods

## arange
- generate array with (start,end,steps)
- syntax : np.arange(start,end,steps)

In [10]:
a=np.arange(1)
print(a)

[0]


In [11]:
# with two parameter
a=np.arange(5,55)
print(a)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54]


In [12]:
# with three parameter or stepping
a=np.arange(1,26,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


## NumPy Zeros 
- Generate arrays of zeros 

In [13]:
x=np.zeros((8,9),dtype="int")
print(x)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [14]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## NumPy Ones
- Generate arrays of ones 

In [15]:
print(np.ones((8,9),dtype=int))

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [16]:
x1=np.ones((5,5))
print(x1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## eye
- Creates an identity matrix

In [17]:
print(np.eye(10,10,dtype='int'))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [18]:
print(np.eye(12, 12,dtype=int)*333)

[[333   0   0   0   0   0   0   0   0   0   0   0]
 [  0 333   0   0   0   0   0   0   0   0   0   0]
 [  0   0 333   0   0   0   0   0   0   0   0   0]
 [  0   0   0 333   0   0   0   0   0   0   0   0]
 [  0   0   0   0 333   0   0   0   0   0   0   0]
 [  0   0   0   0   0 333   0   0   0   0   0   0]
 [  0   0   0   0   0   0 333   0   0   0   0   0]
 [  0   0   0   0   0   0   0 333   0   0   0   0]
 [  0   0   0   0   0   0   0   0 333   0   0   0]
 [  0   0   0   0   0   0   0   0   0 333   0   0]
 [  0   0   0   0   0   0   0   0   0   0 333   0]
 [  0   0   0   0   0   0   0   0   0   0   0 333]]


## Random
- to generate random number in numpy we use rand(no. of matrix,rows,columns)

In [19]:
print(np.random.rand(2,2,3))

[[[0.27147474 0.7366387  0.97302809]
  [0.39231222 0.15690091 0.32671256]]

 [[0.94659058 0.056571   0.48185668]
  [0.81452881 0.39348208 0.84616559]]]


## randint
- Return random integers from low (inclusive) to high (exclusive).
- syntax: np.random.randint(start,end,size(row,col))

In [20]:
import numpy as np
print(np.random.randint(10,20))

16


In [21]:
np.random.randint(500,1000,size=(7,5))

array([[752, 681, 847, 870, 595],
       [839, 747, 937, 901, 951],
       [532, 882, 595, 771, 666],
       [603, 871, 591, 633, 542],
       [744, 755, 629, 552, 679],
       [591, 787, 665, 584, 679],
       [858, 675, 834, 844, 673]])

## Array Attributes and Methods

In [22]:
# creating numpy array using random function
a=np.random.randint(50,100,25) 
print(a)

# creating sorted numpy array using arange
print("sorted numpy array :",np.arange(25))

[73 59 73 52 93 88 82 57 87 76 63 92 99 75 52 57 87 77 73 95 50 69 62 68
 77]
sorted numpy array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


## Reshape
- Returns an array containing the same data with a new shape.

In [23]:
si=np.random.randint(500,1000,size=(2,6))
print(si)
print(si.shape,"\n")

si=si.reshape(6,2)
print(si)
print(si.shape)

[[767 752 989 757 822 564]
 [510 738 930 683 847 863]]
(2, 6) 

[[767 752]
 [989 757]
 [822 564]
 [510 738]
 [930 683]
 [847 863]]
(6, 2)


## Max, Min, Argmax, Argmin
- max : finds maximum value in array
- min : finds minimum value in array
- argmin : finds minimum value index in array
- argmax : finds maximum value index in array

In [24]:
ranarr = np.random.randint(50,100,25)   #(start, end, no. of elements)
ranarr

array([75, 59, 58, 62, 89, 51, 99, 92, 65, 72, 57, 52, 77, 58, 60, 67, 57,
       81, 73, 82, 69, 87, 81, 85, 70])

In [25]:
ranarr.max()#Prints the maximum Number

99

In [26]:
ranarr.min()#Prints the minimum Number

51

In [27]:
#It prints the index position of minimum number
ranarr.argmin()

5

## NumPy Indexing and Selection
- indexing : a[7]
- slicing : a [ no. of rows start : no. of rows end, no. of col start :  no. of col end ]

In [28]:
# creating numpy array
a=np.array([[1,2,4,56,65,6778],[1,2,40,156,615,6778]])
print(a)

[[   1    2    4   56   65 6778]
 [   1    2   40  156  615 6778]]


In [29]:
# indexing 
print(a[1])

[   1    2   40  156  615 6778]


In [30]:
#a[rows slicing, column slicing]
print(a[:,:])

print(a[0,[1,3,5]])

[[   1    2    4   56   65 6778]
 [   1    2   40  156  615 6778]]
[   2   56 6778]


In [31]:
#Creating sample array
arr=np.arange(0,50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
arr[-1]

49

In [33]:
# indexing of array 
print(arr[0])
arr[33]

print(arr[-1])
arr[3:7]
arr[:10]
arr[11:]

0
49


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

## Bracket Indexing and Selection
- The simplest way to pick one or some elements of an array looks very similar to python lists
- syntax: arr[start:end]

In [34]:
#Get values in a range
#92:145
print(arr[42:96],"\n")

#86:136
print(arr[36:87],"\n")

[42 43 44 45 46 47 48 49] 

[36 37 38 39 40 41 42 43 44 45 46 47 48 49] 



In [35]:
## Get values in a range
arr[0:5]
arr[-21]

29

In [36]:
# reverse

print(arr[::-1],"\n")

print(arr[:-21:-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0] 

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30]


## Broadcasting
- Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [37]:
#Setting a value with index range (Broadcasting)
import numpy as np
arr=np.arange(1,15)
#Show
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
#Single value replacing
new=arr[0:6]
new

array([1, 2, 3, 4, 5, 6])

In [39]:
new[5]=555
print(new)
arr

[  1   2   3   4   5 555]


array([  1,   2,   3,   4,   5, 555,   7,   8,   9,  10,  11,  12,  13,
        14])

In [40]:
# returns every object's “identity.
print(id(arr))
print(id(new))


2781678354480
2781678354672


#### Now note the changes also occur in our original array!

In [41]:
arr_new=np.copy(arr[0:10])

print(arr_new,"\n")

arr_new[:]=555
print(arr_new,"\n")
print(arr)

[  1   2   3   4   5 555   7   8   9  10] 

[555 555 555 555 555 555 555 555 555 555] 

[  1   2   3   4   5 555   7   8   9  10  11  12  13  14]


In [42]:
print(id(arr))
print(id(arr_new))

2781678354480
2781678166736


#### Data is not copied, it's a view of the original array! This avoids memory problems!

In [43]:
#To get a copy, need to be explicit
arr=np.arange(80,100)
arr
arr_copy = arr.copy()
arr_copy=arr_copy[0:20]
arr_copy[:]=55
arr_copy

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55])

## Indexing a 2D array (matrices)

In [44]:
import numpy as np

zxc=np.arange(1,31)
print(zxc)
zxc=zxc.reshape(5,6)
zxc

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [45]:
#23,25,28
zxc[[3,4,4],[4,0,3]]

array([23, 25, 28])

In [46]:
zxc[2,2]
#zxc["row","column"]
zxc[3,5]
zxc[4,5]

#10,17,29,26,19
zxc[[1,2,4,4,3,1],[3,4,4,1,0,3]]
#zxc[[row1,row2,row3,row4],[col1,col2,col3,col4]]

array([10, 17, 29, 26, 19, 10])

In [47]:
#Exercise
abc=np.arange(200,250).reshape(10,5)
abc

#Find 217,227,229,244,211,233,245,248,222,225,202

abc[[3,5,5,8],[2,2,4,4]]

array([217, 227, 229, 244])

In [48]:
abc[[3,5,5,8,2,6,9,9,4,5,0],[2,2,4,4,1,3,0,3,2,0,2]]

array([217, 227, 229, 244, 211, 233, 245, 248, 222, 225, 202])

In [49]:
zxc

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [50]:
print(zxc[0:4,0:2],"\n")#only Columns
zxc[0:2,0:3]
zxc[[1,4],:]#Only rows

zxc[:,[5,0,4,3,1,2]]

#zxc[[2,3],:]
#zxc

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]] 



array([[ 6,  1,  5,  4,  2,  3],
       [12,  7, 11, 10,  8,  9],
       [18, 13, 17, 16, 14, 15],
       [24, 19, 23, 22, 20, 21],
       [30, 25, 29, 28, 26, 27]])

### Fancy indexing allows the following

In [51]:
abc=np.arange(0,100).reshape(10,10)
abc

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
#Allows in any order
print(abc[[6,4,2,7]],"\n")#Extracting any Desired Row With Respect to Index Position Number


print(abc[:,[4,2,3]],"\n")#Extracting any Desired Column with Respect to Index Position Number
print(abc[[6,7,8],:])
#abc

[[60 61 62 63 64 65 66 67 68 69]
 [40 41 42 43 44 45 46 47 48 49]
 [20 21 22 23 24 25 26 27 28 29]
 [70 71 72 73 74 75 76 77 78 79]] 

[[ 4  2  3]
 [14 12 13]
 [24 22 23]
 [34 32 33]
 [44 42 43]
 [54 52 53]
 [64 62 63]
 [74 72 73]
 [84 82 83]
 [94 92 93]] 

[[60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]


In [53]:
print(abc[2:7,9])
#90-97
print(abc[9,:8])
#abc[row_start:row_end,column]

print(abc[5,:6])

[29 39 49 59 69]
[90 91 92 93 94 95 96 97]
[50 51 52 53 54 55]


## Selection
- Let's briefly go over how to use brackets for selection based off of comparison operators.

In [54]:
import numpy as np
arr = np.arange(1,21)

ss=[]

for i in arr:
    if i <=5:
        print(i)
        ss.append(i)
print('\n',ss,"\n")
print(arr)

1
2
3
4
5

 [1, 2, 3, 4, 5] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [55]:
# single condition 
arr[(arr<=10) & (arr%2==0)]

#arr[arr>=5]


# multiple condition
#arr[(arr>=5) & (arr<=15)]

array([ 2,  4,  6,  8, 10])

In [56]:
arr[arr >= 4]

bool_arr=arr>=4

In [57]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [58]:
print(arr[bool_arr],"\n")

print(arr[arr >= 4])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [59]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [60]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])