<a href="https://colab.research.google.com/github/coderanandmaurya/numPy/blob/main/numpy_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Operations**
## Arithmetic
You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1=np.arange(0,11)

In [5]:
#arr+arr1

In [6]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [12]:
print(arr)
y=10
z=arr+y
print("X :",arr)
print("Y :",y)
print("Z :",z)

[0 1 2 3 4 5 6 7 8 9]
X : [0 1 2 3 4 5 6 7 8 9]
Y : 10
Z : [10 11 12 13 14 15 16 17 18 19]


## Append


In [13]:
sun=np.append(z,[55,66,77,22,45,44])
sun

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 55, 66, 77, 22, 45, 44])

## Deleting any element in array using index

In [17]:
sun=np.delete(sun,1)
sun

array([10, 12, 13, 14, 15, 16, 17, 18, 19, 77, 22, 45, 44])

## Universal Array Functions

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [19]:
# Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [20]:
np.max(arr) #same as arr.max()
#arr.max()

9

In [21]:
np.min(arr)#Same as arr.min()
#arr.min()

0

In [22]:
arr=np.array([0,30,45,60,90])
sinfun=np.sin(arr)#Sin Thetha
cosfun=np.cos(arr)#Cos Thetha
print(sinfun)
print(cosfun)

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [23]:
arr1=np.arange(0,11)

np.log(arr1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [24]:
np.mean(arr) #Mean

45.0

In [25]:
np.median(arr) #Median

45.0

In [26]:
np.std(arr) #standard Deviation

30.0

In [27]:
np.var(arr) #Variance

900.0