<a href="https://colab.research.google.com/github/coderanandmaurya/numPy/blob/main/Numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import numpy as np

a=[2,4,6,8,10]  # list 1D
print(a)

arr= np.array(a)  #one dimensional array as it has only 1 row
print(arr) 
print(arr.shape)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]
(5,)


## shape attribute

In [110]:
b= np.array([(1,2,3),(4,5,6)]) 
print(b)
print(b.shape)# (no. of rows, no. of columns)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Reshape

In [111]:
# reshape (r,c)   to reshape array
d=b.reshape(6,1)
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## ndim : ndim is used to check dimension of the array

In [112]:
print(arr.ndim)

1


dtype() : # to check data type

In [113]:
a= np.array([(1.6,2.78,3.66)]) 
print(a.dtype) 

float64


## size: to check the size of array

In [114]:
b= np.array([(1,2,3),(4,5,6),(22,44,55)])
print("size of b is ",b.size)

size of b is  9


## Transpose

In [115]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 44, 55]])

In [116]:
tt=np.transpose(b)  # it convert rows into column and via versa
tt

array([[ 1,  4, 22],
       [ 2,  5, 44],
       [ 3,  6, 55]])

## Linspace

In [117]:
a= np.linspace(10,100,10)  # it generate array 
print(a)
print(a.size)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
10


## Min and Max

In [118]:
b= np.array([(1,2,3),(4,5,6)]) 
print(b)

[[1 2 3]
 [4 5 6]]


In [119]:
print(b.max(axis=0))  # axis=0 implies find max values column wise

[4 5 6]


In [120]:
print(b.max(axis=1))  # axis=1 implies find max values row wise

[3 6]


## sum with axis 0(columns) and 1(rows)

In [121]:
b= np.array([(1,2,3),(4,5,6)])
print(b)
b.sum()
print("col addition :",b.sum(axis=0))  # column addition 

print("row additon :",b.sum(axis=1))  # row addition 

#print(np.sum(b,axis=1))

[[1 2 3]
 [4 5 6]]
col addition : [5 7 9]
row additon : [ 6 15]


In [122]:
b= np.array([4,25,9])  # 1D
print(np.sqrt(b))# squareroot of items in array

b= np.array([1,2,3])
np.std(b)# it find the standard deviation of array b

[2. 5. 3.]


0.816496580927726

## addition, multiplication, divison and subtraction of 2 array

In [123]:
a=np.array([(9,8,6),(7,6,5)])
b= np.array([(1,2,3),(4,5,6)])
print("array A")
print(a)
print("array B")
print(b)
c=a+b  # addition of two arrays
print("array C")
print(c)
print(a*b)

print(a/b)


array A
[[9 8 6]
 [7 6 5]]
array B
[[1 2 3]
 [4 5 6]]
array C
[[10 10  9]
 [11 11 11]]
[[ 9 16 18]
 [28 30 30]]
[[9.         4.         2.        ]
 [1.75       1.2        0.83333333]]


## vertical stacking and horizontal stacking of arrays


In [124]:
#stack # LIFO:Last in first out
# queue  # FIFO: First in First Out
[1,2,3,4,4]

a=np.array([(9,8,6),(7,6,5)])
b= np.array([(1,2,3),(4,5,6)])
print(a)
print(b)
print(np.vstack((a,b)))  # vertical stack 

[[9 8 6]
 [7 6 5]]
[[1 2 3]
 [4 5 6]]
[[9 8 6]
 [7 6 5]
 [1 2 3]
 [4 5 6]]


In [125]:
# horizontal stack 
a=np.array([(9,8,6),(7,6,5)])
b= np.array([(1,2,3),(4,5,6)])

print(a)
print(b)
print(np.hstack((a,b)))


[[9 8 6]
 [7 6 5]]
[[1 2 3]
 [4 5 6]]
[[9 8 6 1 2 3]
 [7 6 5 4 5 6]]


## Calculating exponentiall value of array

In [126]:
a= np.array([1,2,3])

print(np.exp(a))  # e*1 is 2.718 ,e*2 is 7.389 and so on
print(a.shape)

[ 2.71828183  7.3890561  20.08553692]
(3,)


In [127]:
a=np.array([1,2,3])
b=np.array([(9,8,6),(7,6,5)])

print(a)
print(np.exp(a))
print(a.shape)

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]
(3,)


## Convert 2 d array into 1d array

In [128]:
b=np.array([(9,8,6),(7,6,5)])
print(b)
print(b.shape)

[[9 8 6]
 [7 6 5]]
(2, 3)


In [129]:
ss=b.ravel() # it convert 2D array into 1D
print(ss)
print(ss.shape)

[9 8 6 7 6 5]
(6,)


##by default argumement to convert 1D to 2D

In [130]:
a=np.array([1,2,3])
b=a.reshape(-1,1)

In [131]:
print(a)
a.ndim

[1 2 3]


1

In [132]:
print(b)
b.ndim

[[1]
 [2]
 [3]]


2

# unique 

In [133]:
marks=np.array([2,5,2,8,5,9,5,4,5])
print(marks)
uni=np.unique(marks)  # it will give u array of unique values in array marks
print(uni)

[2 5 2 8 5 9 5 4 5]
[2 4 5 8 9]


In [134]:
#unique with count
uni,count=np.unique(marks,return_counts=True)  # it will give u array of unique values in array marks
print(count)

[2 1 4 1 1]


## swapping of numbers 

In [135]:
a=5
b=7
a,b=b,a
print(a,b)

7 5
